import QtQuick
import Quickshell
import Quickshell.Hyprland
import Quickshell.Io
import Quickshell.Wayland
import qs.Commons
import qs.Ui
import "CanvasModel.js" as Model

// Infinite canvas for Omarchy.
//
// Every window is a free item on one plane (CanvasModel.js). The overlay is
// the zoomed-out view of that plane; your desktop is a viewport onto it.
// Picking a window (or an empty spot) zooms in and "lands": the workspace
// shows that part of the canvas, with every window in view floating at its
// canvas position — pulled over from other workspaces if needed.
//
// Toggled with `omarchy-shell shell toggle io.github.lmajs.infiniarchy '{}'` (bound by
// ~/.config/hypr/infiniarchy.lua, generated by the infiniarchy CLI).

Item {
  id: root

  property var shell: null
  property var manifest: null
  readonly property string pluginId: (manifest && manifest.id) || "io.github.lmajs.infiniarchy"

  // Host contract: `opened` is what omarchy-shell reads for toggle().
  property bool opened: false
  property bool closing: false
  property string view: "canvas"

  readonly property string home: Quickshell.env("HOME")
  // The CLI ships next to the plugin, so this works for `omarchy plugin add` installs too.
  readonly property string cli: decodeURIComponent(String(Qt.resolvedUrl("../bin/infiniarchy")).replace(/^file:\/\//, ""))
  readonly property string configPath: home + "/.config/infiniarchy/config.json"
  readonly property string stateDir: home + "/.local/state/infiniarchy"
  readonly property var defaults: ({ hotkey: "RALT + Q", lens: 0.55, liveThumbnails: true, showMinimap: true, showLabels: false, canvasDesktop: false, showDots: true, attachWindows: true, flatView: true, showHints: true })
  property var cfg: defaults
  readonly property bool canvasDesktop: cfg.canvasDesktop === true

  // ── model ───────────────────────────────────────────────────────────
  property var layout: Model.emptyLayout()
  property var items: []            // canvas items, nav order
  property var byAddr: ({})
  property var order: []            // addresses, for the ScriptModel
  property var bounds: ({ x: 0, y: 0, w: 1920, h: 1080 })
  property var mon: ({ id: -1, x: 0, y: 0, w: 1920, h: 1080 })
  property var monitors: ({})
  property var wsMon: ({})
  property int activeWs: 1
  property var toplevels: ({})
  property bool hasSnapshot: false
  property string selectedAddr: ""
  property string hoveredAddr: ""
  property var zBoost: ({})
  property int zTop: 20000

  // Drag state (canvas coords of the dragged window's top-left).
  property string dragAddr: ""
  property real dragX: 0
  property real dragY: 0
  // Chained windows ride along: addr -> start rect; dragStart is the grabbed one's.
  property var dragGroup: ({})
  property var dragStart: ({ x: 0, y: 0 })
  property var picked: ({})          // right-drag selection: addr -> true
  property var marquee: null         // selection box in canvas coords while dragging
  property string toastText: ""
  readonly property bool attachEnabled: cfg.attachWindows !== false
  readonly property var links: layout.links || []
  readonly property var linkKeys: links.map(function(k) { return k[0] + "|" + k[1] })

  // Where the close animation should land (set by land()/focusItem()).
  property var closeTarget: null
  property string closeFocus: ""

  // ── view: scene px = world * zoom + pan ─────────────────────────────
  property real zoom: 1
  property real panX: 0
  property real panY: 0
  property real lensStrength: 0
  property real reveal: 0
  readonly property real targetLens: Math.max(0, Math.min(1, Number(cfg.lens === undefined ? 0.55 : cfg.lens)))
  readonly property real minZoom: 0.03
  readonly property real maxZoom: 1.6
  readonly property real sceneW: panel.width > 0 ? panel.width : 1920
  readonly property real sceneH: panel.height > 0 ? panel.height : 1080
  readonly property var viewport: ({ x: -panX / zoom, y: -panY / zoom, w: sceneW / zoom, h: sceneH / zoom })

  readonly property color fg: Color.foreground
  readonly property color bg: Color.background
  readonly property color accent: Color.accent
  readonly property string fontFamily: Style.font.menuFamily

  function itemRect(addr) {
    var it = byAddr[addr]
    if (!it) return null
    if (dragAddr && dragGroup[addr]) {
      var g = dragGroup[addr]
      return { x: g.x + dragX - dragStart.x, y: g.y + dragY - dragStart.y, w: it.w, h: it.h }
    }
    return { x: it.x, y: it.y, w: it.w, h: it.h }
  }

  // ── config + layout files ───────────────────────────────────────────

  FileView {
    id: configFile
    path: root.configPath
    watchChanges: true
    printErrors: false
    onFileChanged: reload()
    onLoaded: {
      try {
        var parsed = JSON.parse(text())
        var next = ({})
        for (var d in root.defaults) next[d] = root.defaults[d]
        for (var k in parsed) next[k] = parsed[k]
        root.cfg = next
      } catch (e) {
        console.warn("canvas: bad config", e)
      }
    }
  }

  // Watched so external writers (`infiniarchy release`) take effect; the
  // echo of our own writes is recognised by content and ignored.
  property string lastWrittenLayout: ""
  FileView {
    id: layoutFile
    path: root.stateDir + "/layout.json"
    watchChanges: true
    printErrors: false
    atomicWrites: true
    onFileChanged: reload()
    onLoaded: {
      var t = text()
      if (t === root.lastWrittenLayout) return
      var raw = null
      try { raw = JSON.parse(t || "{}") } catch (e) { raw = null }
      root.layout = Model.normalizeLayout(raw)
    }
  }

  Component.onCompleted: {
    Quickshell.execDetached(["mkdir", "-p", root.stateDir])
    refreshWallpaper()
  }

  function loadLayout() { layoutFile.reload() }

  Timer {
    id: saveTimer
    interval: 250
    onTriggered: {
      root.lastWrittenLayout = JSON.stringify(root.layout, null, 1)
      layoutFile.setText(root.lastWrittenLayout)
    }
  }
  function saveLayout() { saveTimer.restart() }

  // ── CLI / Hyprland bridges ──────────────────────────────────────────

  Component {
    id: cliProcess
    Process {
      id: proc
      property var callback: null
      stdout: StdioCollector {
        onStreamFinished: {
          var res = null
          try { res = JSON.parse(text) } catch (e) { res = { ok: false, error: String(text || "no output").trim() } }
          if (proc.callback) proc.callback(res)
          proc.destroy()
        }
      }
    }
  }

  // Omarchy swaps wallpapers by repointing a symlink, and an unchanged URL
  // never reloads, so resolve the real file (and its mtime) on every open.
  readonly property string wallpaperLink: home + "/.local/state/omarchy/current/background"
  property string wallpaper: "file://" + wallpaperLink
  Process {
    id: wallpaperProbe
    command: ["sh", "-c", 'f=$(readlink -f "$1") && printf "%s\\n%s" "$f" "$(stat -c %Y "$f")"', "sh", root.wallpaperLink]
    stdout: StdioCollector {
      onStreamFinished: {
        var lines = String(text).trim().split("\n")
        if (lines[0]) root.wallpaper = "file://" + lines[0] + (lines[1] ? "?v=" + lines[1] : "")
      }
    }
  }
  function refreshWallpaper() { wallpaperProbe.running = false; wallpaperProbe.running = true }

  function runCli(args, callback) {
    var p = cliProcess.createObject(root, { command: [root.cli, "--json"].concat(args), callback: callback || null })
    p.running = true
  }

  Component {
    id: evalProcess
    Process {
      id: ep
      stdout: StdioCollector {
        onStreamFinished: {
          if (String(text).indexOf("error") >= 0) console.warn("canvas: hyprctl eval:", text)
          ep.destroy()
        }
      }
    }
  }

  function hyprEval(lua) {
    if (!lua) return
    var p = evalProcess.createObject(root, { command: ["hyprctl", "eval", lua] })
    p.running = true
  }

  function startRecording() { Quickshell.execDetached([root.cli, "record", "start"]) }
  function stopRecording() { Quickshell.execDetached([root.cli, "record", "stop"]) }

  // ── snapshots ───────────────────────────────────────────────────────

  property bool snapshotQueued: false
  property bool snapshotInitial: false
  property bool pendingManage: false

  Process {
    id: snapshotProc
    command: ["sh", "-c", "printf '{\"clients\":'; hyprctl -j clients; printf ',\"workspaces\":'; hyprctl -j workspaces; printf ',\"monitors\":'; hyprctl -j monitors; printf '}'"]
    stdout: StdioCollector { onStreamFinished: root.applySnapshot(text) }
    onExited: {
      if (root.snapshotQueued) {
        root.snapshotQueued = false
        snapshotProc.running = true
      }
    }
  }

  function refresh(initial) {
    if (initial) snapshotInitial = true
    if (snapshotProc.running) { snapshotQueued = true; return }
    snapshotProc.running = true
  }

  function rebuildToplevels() {
    var map = ({})
    var list = Hyprland.toplevels.values
    for (var i = 0; i < list.length; i++) map[Model.normAddress(list[i].address)] = list[i]
    toplevels = map
  }

  function monFor(ws) {
    var m = monitors[wsMon[ws]]
    if (!m) return mon
    var s = Model.logicalSize(m)
    return { id: m.id, x: Number(m.x), y: Number(m.y), w: s.w, h: s.h }
  }

  function setItems(list) {
    var map = ({}), addrs = []
    for (var i = 0; i < list.length; i++) { map[list[i].address] = list[i]; addrs.push(list[i].address) }
    byAddr = map
    items = list
    order = addrs
    bounds = Model.boundsOf(list)
  }

  function applySnapshot(raw) {
    var data
    try { data = JSON.parse(raw) } catch (e) { console.warn("canvas: bad hyprctl output", e); return }
    var model = Model.build(data, layout, Date.now(), canvasDesktop)
    monitors = model.monitors
    wsMon = model.wsMon
    mon = model.monitor
    activeWs = model.activeWs
    var lay = model.layout
    var list = model.items

    // New windows on a canvas workspace open next to the window you were
    // using, inside the visible viewport, and float there on the desktop.
    var landed = []
    if (canvasDesktop) {
      var placed = list.filter(function(it) { return !it.isNew })
      for (var i = 0; i < list.length; i++) {
        var it = list[i]
        if (!it.isNew || !it.onCanvasWs || it.special || it.fullscreen) continue
        var vp = lay.viewports[String(it.workspaceId)]
        var m = monFor(it.workspaceId)
        var view = { x: Number(vp.x), y: Number(vp.y), w: m.w, h: m.h }
        var anchor = null
        for (var p = 0; p < placed.length; p++) {
          var c = placed[p]
          if (c.workspaceId === it.workspaceId && Model.intersects(c, view, 0) && (!anchor || c.focusRank < anchor.focusRank)) anchor = c
        }
        var spot = Model.place(it.w, it.h, placed, anchor, view)
        it.x = spot.x; it.y = spot.y
        lay.windows[it.address].x = spot.x
        lay.windows[it.address].y = spot.y
        placed.push(it)
        var plan = Model.landingPlan([it], it.workspaceId, { x: view.x, y: view.y }, m)
        if (plan.lua) {
          hyprEval(plan.lua)
          if (!lay.managed[it.address]) lay.managed[it.address] = { ws: it.workspaceId, floating: false }
          landed.push(it.address)
        }
      }
    }

    layout = lay
    saveLayout()
    pendingManage = false
    if (!opened && !closing) return

    rebuildToplevels()
    setItems(list)
    hasSnapshot = true
    if (!byAddr[selectedAddr]) selectedAddr = model.focused || (list.length ? list[0].address : "")

    if (snapshotInitial) {
      snapshotInitial = false
      introAnimation()
    }
  }

  Connections {
    target: Hyprland
    function onRawEvent(event) {
      var name = event ? String(event.name || "") : ""
      if (name.indexOf("openwindow") === 0) {
        root.pendingManage = true
        manageDebounce.restart()
        return
      }
      if (!root.opened) return
      if (name.indexOf("closewindow") === 0 || name.indexOf("movewindow") === 0 ||
          name.indexOf("windowtitle") === 0 || name.indexOf("changefloatingmode") === 0 || name.indexOf("fullscreen") === 0) {
        refreshDebounce.restart()
      }
    }
  }

  Timer { id: refreshDebounce; interval: 150; onTriggered: root.refresh(false) }
  // Give Hyprland a moment to map + size the new window before placing it.
  Timer { id: manageDebounce; interval: 220; onTriggered: root.refresh(false) }

  // ── view math ───────────────────────────────────────────────────────

  function viewportPose(vp, m) {
    var z = Math.min(sceneW / m.w, sceneH / m.h)
    return { zoom: z, cx: Number(vp.x) + m.w / 2, cy: Number(vp.y) + m.h / 2 }
  }

  // Pose where item `f`'s canvas rect lines up with its real on-screen rect.
  // Line the thumbnail up with the real window (scale from the tighter axis in
  // case the aspect ratios momentarily differ), or the window visibly jumps
  // when the overlay hides.
  function morphPose(f) {
    var s = Math.min(f.w / Math.max(1, f.realW), f.h / Math.max(1, f.realH))
    var z = Math.max(minZoom, Math.min(maxZoom, 1 / Math.max(0.0001, s)))
    var realCx = f.realX - f.monX + f.realW / 2, realCy = f.realY - f.monY + f.realH / 2
    return { zoom: z, cx: f.x + f.w / 2 - (realCx - sceneW / 2) / z, cy: f.y + f.h / 2 - (realCy - sceneH / 2) / z }
  }

  // Pose that makes the canvas look like the current desktop.
  function desktopPose() {
    var vp = layout.viewports[String(activeWs)]
    if (vp && canvasDesktop) return viewportPose(vp, mon)
    var f = null
    for (var i = 0; i < items.length; i++) if (items[i].focused && items[i].workspaceId === activeWs) f = items[i]
    return f ? morphPose(f) : fitPose()
  }

  function fitPose() {
    var b = bounds
    var mx = sceneW * 0.14, my = sceneH * 0.16
    var z = Math.min((sceneW - mx * 2) / Math.max(1, b.w), (sceneH - my * 2) / Math.max(1, b.h))
    z = Math.max(minZoom, Math.min(0.5, z))
    return { zoom: z, cx: b.x + b.w / 2, cy: b.y + b.h / 2 }
  }

  function currentPose() {
    return { zoom: zoom, cx: (sceneW / 2 - panX) / zoom, cy: (sceneH / 2 - panY) / zoom }
  }

  function setPose(z, cx, cy) {
    zoom = z
    panX = sceneW / 2 - cx * z
    panY = sceneH / 2 - cy * z
  }

  // Log-zoom path so zoom speed feels constant.
  property var animFrom: null
  property var animTo: null
  property real animT: 0
  property var animDone: null
  onAnimTChanged: {
    if (!animFrom || !animTo) return
    var t = animT
    var z = Math.exp(Math.log(animFrom.zoom) + (Math.log(animTo.zoom) - Math.log(animFrom.zoom)) * t)
    setPose(z, animFrom.cx + (animTo.cx - animFrom.cx) * t, animFrom.cy + (animTo.cy - animFrom.cy) * t)
    lensStrength = animFrom.lens + (animTo.lens - animFrom.lens) * t
    reveal = animFrom.reveal + (animTo.reveal - animFrom.reveal) * t
  }

  NumberAnimation {
    id: poseAnim
    target: root
    property: "animT"
    from: 0
    to: 1
    easing.type: Easing.OutCubic
    onFinished: {
      var done = root.animDone
      root.animDone = null
      if (done) done()
    }
  }

  function animateTo(pose, lens, rev, duration, done) {
    poseAnim.stop()
    var from = currentPose()
    from.lens = lensStrength
    from.reveal = reveal
    animFrom = from
    animTo = { zoom: pose.zoom, cx: pose.cx, cy: pose.cy, lens: lens, reveal: rev }
    animDone = done || null
    animT = 0
    poseAnim.duration = duration
    poseAnim.start()
  }

  function introAnimation() {
    var start = desktopPose()
    setPose(start.zoom, start.cx, start.cy)
    lensStrength = 0
    reveal = 0
    animateTo(fitPose(), targetLens, 1, 420)
  }

  // Smooth zoom around a scene point; wheel notches retarget the animation.
  function zoomAt(sx, sy, factor) {
    if (flat) {
      if (factor < 1) exitFlat(sx, sy)
      return
    }
    var base = poseAnim.running && animTo ? animTo.zoom : zoom
    var nz = Math.max(minZoom, Math.min(maxZoom, base * factor))
    var wx = (sx - panX) / zoom, wy = (sy - panY) / zoom
    if (factor > 1 && flatEnabled && nz >= flatThreshold * flatZoom) {
      enterFlat(sx, sy)
      return
    }
    var npx = sx - wx * nz, npy = sy - wy * nz
    animateTo({ zoom: nz, cx: (sceneW / 2 - npx) / nz, cy: (sceneH / 2 - npy) / nz }, lensStrength, reveal, 140)
  }

  // Flat view (the reference's second mode): zoom in far enough and the curved,
  // dimmed overview lights up and jumps to a straight 1:1 view of the canvas.
  // Zooming out drops back into the curved overview.
  property bool flat: false
  property real flatness: 0
  Behavior on flatness { NumberAnimation { duration: 170; easing.type: Easing.OutQuad } }
  onFlatChanged: flatness = flat ? 1 : 0
  readonly property bool flatEnabled: cfg.flatView !== false
  readonly property real flatZoom: sceneW / Math.max(1, mon.w)
  readonly property real flatThreshold: 0.72

  function enterFlat(sx, sy) {
    if (flat || !opened || closing) return
    var wx = (sx - panX) / zoom, wy = (sy - panY) / zoom
    var fz = flatZoom
    var npx = Math.round(sx - wx * fz), npy = Math.round(sy - wy * fz)
    flat = true
    hoveredAddr = ""
    lightUp.restart()
    animateTo({ zoom: fz, cx: (sceneW / 2 - npx) / fz, cy: (sceneH / 2 - npy) / fz }, 0, reveal, 170)
  }

  function exitFlat(sx, sy) {
    if (!flat) return
    var wx = (sx - panX) / zoom, wy = (sy - panY) / zoom
    var z = flatZoom * 0.5
    var npx = sx - wx * z, npy = sy - wy * z
    flat = false
    animateTo({ zoom: z, cx: (sceneW / 2 - npx) / z, cy: (sceneH / 2 - npy) / z }, targetLens, reveal, 260)
  }

  function fitAll() {
    flat = false
    animateTo(fitPose(), targetLens, 1, 260)
  }

  function panBy(dx, dy) {
    poseAnim.stop()
    panX += dx
    panY += dy
  }

  function revealItem(addr) {
    var r = itemRect(addr)
    if (!r) return
    var sx0 = r.x * zoom + panX, sy0 = r.y * zoom + panY
    var sx1 = sx0 + r.w * zoom, sy1 = sy0 + r.h * zoom
    var mx = sceneW * 0.18, my = sceneH * 0.18
    if (sx0 >= mx && sy0 >= my && sx1 <= sceneW - mx && sy1 <= sceneH - my) return
    var fit = Math.min((sceneW - mx * 2) / r.w, (sceneH - my * 2) / r.h)
    animateTo({ zoom: Math.min(zoom, fit), cx: r.x + r.w / 2, cy: r.y + r.h / 2 }, lensStrength, 1, 220)
  }

  // Must match shaders/lens.frag.
  function lensFactor(px, py) {
    var aspect = sceneW / sceneH
    var r2 = px * aspect * px * aspect + py * py
    var k = lensStrength * 0.42
    return (1 + k * r2) / (1 + k * 0.18)
  }

  function lensMap(mx, my) {
    var px = mx / sceneW - 0.5, py = my / sceneH - 0.5
    var f = lensFactor(px, py)
    var u = 0.5 + px * f, v = 0.5 + py * f
    if (u < 0 || u > 1 || v < 0 || v > 1) return null
    return { x: u * sceneW, y: v * sceneH }
  }

  // Screen point that shows scene point (sx, sy) — inverse of lensMap.
  function lensUnmap(sx, sy) {
    var tu = sx / sceneW - 0.5, tv = sy / sceneH - 0.5
    var px = tu, py = tv
    for (var i = 0; i < 30; i++) {
      var f = lensFactor(px, py)
      px = tu / f
      py = tv / f
    }
    return { x: (px + 0.5) * sceneW, y: (py + 0.5) * sceneH }
  }

  function worldAt(mx, my) {
    var s = lensMap(mx, my)
    if (!s) return null
    return { x: (s.x - panX) / zoom, y: (s.y - panY) / zoom }
  }

  function zOf(addr) {
    var it = byAddr[addr]
    return (zBoost[addr] || 0) + (it ? it.z : 0)
  }

  function itemAt(mx, my) {
    var p = worldAt(mx, my)
    if (!p) return ""
    var best = "", bestZ = -1
    for (var i = 0; i < items.length; i++) {
      var r = itemRect(items[i].address)
      var z = zOf(items[i].address)
      if (p.x >= r.x && p.x <= r.x + r.w && p.y >= r.y && p.y <= r.y + r.h && z >= bestZ) {
        best = items[i].address
        bestZ = z
      }
    }
    return best
  }

  function raise(addr) {
    var zb = ({})
    for (var k in zBoost) zb[k] = zBoost[k]
    zTop += 1
    zb[addr] = zTop
    zBoost = zb
  }

  // ── arranging ───────────────────────────────────────────────────────

  // moves: { addr: { x, y } }. With `attach`, windows that end up edge to
  // edge with a window outside the moved set get chained to it.
  function commitMoves(moves, attach) {
    var lay = Model.cloneLayout(layout)
    var lua = []
    var list = items.map(function(o) {
      var mv = moves[o.address]
      if (!mv) return o
      var copy = ({})
      for (var k in o) copy[k] = o[k]
      copy.x = Math.round(mv.x)
      copy.y = Math.round(mv.y)
      var e = lay.windows[o.address] || {}
      e.x = copy.x; e.y = copy.y; e.w = Math.round(copy.w); e.h = Math.round(copy.h)
      e.cls = copy.appClass; e.title = copy.title; e.seen = Date.now()
      lay.windows[o.address] = e
      // A window on a canvas workspace moves on the real desktop right away.
      var vp = lay.viewports[String(copy.workspaceId)]
      if (canvasDesktop && vp && copy.floating && !copy.fullscreen) {
        var m = monFor(copy.workspaceId)
        lua.push("hl.dispatch(hl.dsp.window.move({ x = " + Math.round(m.x + copy.x - vp.x) + ", y = " + Math.round(m.y + copy.y - vp.y) +
                 ", window = 'address:" + o.address + "' }))")
      }
      return copy
    })
    if (attach && attachEnabled) {
      for (var i = 0; i < list.length; i++) {
        if (!moves[list[i].address]) continue
        for (var j = 0; j < list.length; j++) {
          var o = list[j]
          if (moves[o.address] || o.special) continue
          if (Model.adjacent(list[i], o) && !Model.hasLink(lay.links, list[i].address, o.address))
            lay.links.push([list[i].address, o.address])
        }
      }
    }
    layout = lay
    setItems(list)
    saveLayout()
    if (lua.length) hyprEval(lua.join("\n"))
  }

  function commitMove(addr, x, y) {
    var mv = ({})
    mv[addr] = { x: x, y: y }
    commitMoves(mv, false)
  }

  function groupMembers(addr) {
    return attachEnabled ? Model.groupOf(addr, links) : [addr]
  }

  function nudgeSelected(dx, dy) {
    if (!byAddr[selectedAddr]) return
    var group = groupMembers(selectedAddr)
    var moves = ({})
    for (var i = 0; i < group.length; i++) {
      var r = itemRect(group[i])
      if (r) moves[group[i]] = { x: r.x + dx, y: r.y + dy }
    }
    commitMoves(moves, false)
    raise(selectedAddr)
  }

  function unlink(key) {
    var parts = key.split("|")
    var lay = Model.cloneLayout(layout)
    lay.links = lay.links.filter(function(k) { return !((k[0] === parts[0] && k[1] === parts[1]) || (k[0] === parts[1] && k[1] === parts[0])) })
    layout = lay
    saveLayout()
  }

  function pickedList() {
    var out = []
    for (var k in picked) if (picked[k] && byAddr[k]) out.push(k)
    return out
  }

  function selectInBox(box) {
    var next = ({})
    for (var i = 0; i < items.length; i++) {
      var r = itemRect(items[i].address)
      if (Model.intersects(r, box, 0)) next[items[i].address] = true
    }
    picked = next
  }

  function startDrag(addr) {
    poseAnim.stop()
    var roots = picked[addr] ? pickedList() : [addr]
    var g = ({})
    for (var i = 0; i < roots.length; i++) {
      var members = groupMembers(roots[i])
      for (var j = 0; j < members.length; j++) {
        var rr = itemRect(members[j])
        if (rr) g[members[j]] = { x: rr.x, y: rr.y }
      }
    }
    var r0 = itemRect(addr)
    dragGroup = g
    dragStart = { x: r0.x, y: r0.y }
    dragX = r0.x
    dragY = r0.y
    dragAddr = addr
    selectedAddr = addr
    raise(addr)
  }

  function endDrag() {
    var moves = ({})
    for (var m in dragGroup) moves[m] = itemRect(m)
    dragAddr = ""
    dragGroup = ({})
    commitMoves(moves, true)
  }

  // Right-click on a window: a lone window drops all its links; a window in
  // the selection cuts the selection loose from everything unselected but
  // keeps the links inside the selection.
  function unlinkFor(addr) {
    var sel = picked[addr] ? picked : null
    var lay = Model.cloneLayout(layout)
    var before = lay.links.length
    lay.links = lay.links.filter(function(k) {
      if (sel) return !!sel[k[0]] === !!sel[k[1]]
      return k[0] !== addr && k[1] !== addr
    })
    var removed = before - lay.links.length
    layout = lay
    saveLayout()
    toast(removed ? "Unlinked " + removed + (removed === 1 ? " connection" : " connections")
                  : "Nothing to unlink")
  }

  function closeWindow(addr) {
    var it = byAddr[addr]
    if (!it) return
    hyprEval("hl.dispatch(hl.dsp.window.close({ window = 'address:" + addr + "' }))")
    if (picked[addr]) {
      var next = ({})
      for (var k in picked) if (k !== addr) next[k] = picked[k]
      picked = next
    }
    toast("Closed " + (it.title || it.appClass || "window"))
  }

  function toast(text) {
    toastText = text
    toastTimer.restart()
  }

  Timer { id: toastTimer; interval: 1800; onTriggered: root.toastText = "" }

  function unlinkAll(addr) {
    var lay = Model.cloneLayout(layout)
    lay.links = lay.links.filter(function(k) { return k[0] !== addr && k[1] !== addr })
    layout = lay
    saveLayout()
  }

  // Scene position of a link's chain badge.
  function linkScenePos(key) {
    var parts = key.split("|")
    var a = itemRect(parts[0]), b = itemRect(parts[1])
    if (!a || !b) return null
    var an = Model.linkAnchor(a, b)
    return { x: an.x * zoom + panX, y: an.y * zoom + panY, an: an }
  }



  function snapOthers(addr) {
    var out = []
    for (var i = 0; i < items.length; i++) if (items[i].address !== addr && !dragGroup[items[i].address]) out.push(items[i])
    return out
  }

  // ── landing ─────────────────────────────────────────────────────────

  // Remember where a window lived before the canvas first moved it, so
  // `infiniarchy release` can send it home.
  function markManaged(lay, addrs) {
    for (var i = 0; i < addrs.length; i++) {
      var a = addrs[i]
      if (lay.managed[a] && typeof lay.managed[a] === "object") continue
      var it = byAddr[a]
      lay.managed[a] = { ws: it ? it.workspaceId : null, floating: it ? it.floating : false }
    }
  }

  // Make workspace `ws` show canvas viewport `vp` and focus `focusAddr`.
  function land(ws, vp, focusAddr) {
    var m = monFor(ws)
    var plan = Model.landingPlan(items, ws, vp, m)
    var lay = Model.cloneLayout(layout)
    lay.viewports[String(ws)] = { x: Math.round(vp.x), y: Math.round(vp.y) }
    markManaged(lay, plan.moved)
    layout = lay
    saveLayout()
    var lua = plan.lua
    lua += "\n" + (focusAddr ? "hl.dispatch(hl.dsp.focus({ window = 'address:" + focusAddr + "' }))"
                             : "hl.dispatch(hl.dsp.focus({ workspace = " + ws + " }))")
    hyprEval(lua)
    closeTarget = viewportPose(vp, m)
  }

  function viewportFor(ws, it) {
    var m = monFor(ws)
    var vp = layout.viewports[String(ws)]
    if (vp && it) {
      var view = { x: Number(vp.x), y: Number(vp.y), w: m.w, h: m.h }
      if (it.x >= view.x && it.y >= view.y && it.x + it.w <= view.x + view.w && it.y + it.h <= view.y + view.h) return view
    }
    return { x: Math.round(it.x + it.w / 2 - m.w / 2), y: Math.round(it.y + it.h / 2 - m.h / 2) }
  }

  function focusItem(addr) {
    var it = byAddr[addr]
    if (!it) return
    selectedAddr = addr
    closeFocus = addr
    if (!canvasDesktop || it.special || it.fullscreen) {
      Quickshell.execDetached(["hyprctl", "dispatch", "hl.dsp.focus({ window = 'address:" + addr + "' })"])
      closeTarget = it.special ? null : morphPose(it)
    } else {
      land(it.workspaceId, viewportFor(it.workspaceId, it), addr)
    }
    dismiss()
  }

  function landAt(wx, wy) {
    if (!canvasDesktop) return
    var m = monFor(activeWs)
    land(activeWs, { x: Math.round(wx - m.w / 2), y: Math.round(wy - m.h / 2) }, "")
    dismiss()
  }

  function selectBy(dx, dy) {
    var n = Model.neighbor(items, selectedAddr, dx, dy)
    if (n) { selectedAddr = n; revealItem(n) }
  }

  // Q / E: previous / next window in reading order, centred in the view.
  function jump(delta) {
    if (!items.length) return
    var idx = -1
    for (var i = 0; i < items.length; i++) if (items[i].address === selectedAddr) idx = i
    var next = items[((idx < 0 ? (delta > 0 ? -1 : 0) : idx) + delta + items.length) % items.length]
    selectedAddr = next.address
    var r = itemRect(next.address)
    var z = poseAnim.running && animTo ? animTo.zoom : zoom
    animateTo({ zoom: z, cx: r.x + r.w / 2, cy: r.y + r.h / 2 }, flat ? 0 : lensStrength, reveal, 240)
  }

  // WASD: smooth panning while the keys are held.
  property var heldPan: ({})
  readonly property bool keyPanning: !!(heldPan.w || heldPan.a || heldPan.s || heldPan.d)
  property real lastPanTick: 0
  function holdPan(key, down) {
    var next = ({})
    for (var k in heldPan) next[k] = heldPan[k]
    next[key] = down
    heldPan = next
    lastPanTick = Date.now()
  }
  Timer {
    interval: 8
    repeat: true
    running: root.keyPanning && root.opened
    onTriggered: {
      var now = Date.now()
      var dt = Math.min(0.05, (now - root.lastPanTick) / 1000)
      root.lastPanTick = now
      var speed = 1300
      var dx = (root.heldPan.a ? 1 : 0) - (root.heldPan.d ? 1 : 0)
      var dy = (root.heldPan.w ? 1 : 0) - (root.heldPan.s ? 1 : 0)
      if (dx || dy) root.panBy(dx * speed * dt, dy * speed * dt)
    }
  }

  function cycle(delta) {
    if (!items.length) return
    var idx = 0
    for (var i = 0; i < items.length; i++) if (items[i].address === selectedAddr) idx = i
    selectedAddr = items[(idx + delta + items.length) % items.length].address
    revealItem(selectedAddr)
  }

  // ── host contract ───────────────────────────────────────────────────

  function pickScreen() {
    var name = Hyprland.focusedMonitor ? Hyprland.focusedMonitor.name : ""
    var screens = Quickshell.screens
    for (var i = 0; i < screens.length; i++) if (screens[i].name === name) return screens[i]
    return screens.length ? screens[0] : null
  }

  function open(payloadJson) {
    var payload = ({})
    try { payload = JSON.parse(payloadJson || "{}") } catch (e) { payload = ({}) }
    var wantSettings = payload.view === "settings"
    if (root.opened && !root.closing) {
      root.view = wantSettings ? "settings" : root.view
      return
    }
    refreshWallpaper()
    poseAnim.stop()
    root.closeTarget = null
    root.closeFocus = ""
    root.hoveredAddr = ""
    root.dragAddr = ""
    root.view = wantSettings ? "settings" : "canvas"
    root.flat = false
    settings.reset()
    if (!root.closing) panel.screen = root.pickScreen()
    root.opened = true
    root.closing = false
    configFile.reload()
    refresh(true)
    Qt.callLater(function() { keyCatcher.forceActiveFocus() })
  }

  // Called by the host (hotkey toggle / shell hide) and by dismiss().
  function close() {
    if (!root.opened) return
    if (settings.recording) settings.cancelRecording()
    root.dragAddr = ""
    root.dragGroup = ({})
    root.marquee = null
    root.picked = ({})
    root.heldPan = ({})
    // closing first: `visible` is opened || closing, and a single false in
    // between unmaps the layer surface (Hyprland then fades it back in).
    root.closing = true
    root.opened = false
    if (!root.hasSnapshot) { finishClose(); return }
    var target = root.closeTarget
    if (!target) {
      // Esc on a canvas workspace re-lands the same viewport so windows you
      // dragged into or out of view follow on the desktop.
      var vp = root.layout.viewports[String(root.activeWs)]
      if (root.canvasDesktop && vp) {
        var plan = Model.landingPlan(root.items, root.activeWs, vp, root.mon)
        if (plan.lua) {
          var lay = Model.cloneLayout(root.layout)
          markManaged(lay, plan.moved)
          root.layout = lay
          root.saveLayout()
          root.hyprEval(plan.lua)
        }
      }
      target = desktopPose()
    }
    animateTo(target, 0, 0, root.closeTarget ? 360 : 260, finishClose)
  }

  function finishClose() {
    root.flat = false
    root.closing = false
    root.hasSnapshot = false
    root.closeTarget = null
    root.closeFocus = ""
    setItems([])
  }

  // `omarchy-shell shell call io.github.lmajs.infiniarchy look '{"cx":0,"cy":0,"zoom":0.5}'`
  // frames a canvas spot; `{"address":"0x…"}` centres a window instead.
  function look(arg) {
    var a = {}
    try { a = JSON.parse(arg || "{}") } catch (e) { return "bad json" }
    var p = currentPose()
    if (a.address) {
      var r = itemRect(a.address)
      if (!r) return "unknown window"
      selectedAddr = a.address
      p.cx = r.x + r.w / 2; p.cy = r.y + r.h / 2
    }
    if (a.cx !== undefined) p.cx = Number(a.cx)
    if (a.cy !== undefined) p.cy = Number(a.cy)
    if (a.zoom !== undefined) p.zoom = Math.max(minZoom, Math.min(maxZoom, Number(a.zoom)))
    flat = false
    animateTo(p, targetLens, reveal, Number(a.duration) || 260)
    return "ok"
  }

  // `omarchy-shell shell call io.github.lmajs.infiniarchy status ''` — used by tests.
  function status(arg) {
    var list = []
    for (var i = 0; i < items.length; i++) {
      var it = items[i]
      var r = itemRect(it.address)
      var c = lensUnmap((r.x + r.w / 2) * zoom + panX, (r.y + r.h / 2) * zoom + panY)
      list.push({ a: it.address, cls: it.appClass, ws: it.workspaceId, x: Math.round(r.x), y: Math.round(r.y), w: Math.round(r.w), h: Math.round(r.h),
                  fl: it.floating, sx: Math.round(c.x), sy: Math.round(c.y) })
    }
    return JSON.stringify({
      opened: opened, closing: closing, view: view, windows: items.length,
      zoom: Math.round(zoom * 1000) / 1000, lens: Math.round(lensStrength * 100) / 100,
      selected: selectedAddr, hovered: hoveredAddr, dragging: dragAddr, hotkey: cfg.hotkey, links: links,
      picked: pickedList(), toast: toastText, cli: cli, wallpaper: wallpaper,
      activeWs: activeWs, viewports: layout.viewports, canvasDesktop: canvasDesktop, flat: flat,
      settingsPhase: settings.phase, captured: settings.captured, message: settings.message,
      items: list
    })
  }

  function dismiss() {
    if (root.shell && typeof root.shell.hide === "function") root.shell.hide(root.pluginId)
    else root.close()
  }

  // ── UI ──────────────────────────────────────────────────────────────

  ScriptModel {
    id: tileModel
    values: root.order
  }

  PanelWindow {
    id: panel
    visible: root.opened || root.closing
    anchors { top: true; bottom: true; left: true; right: true }
    color: "transparent"
    exclusionMode: ExclusionMode.Ignore
    WlrLayershell.namespace: "infiniarchy"
    WlrLayershell.layer: WlrLayer.Overlay
    // Constant while the window is up: changing it makes Quickshell re-create
    // the layer surface, which flashes the desktop mid-animation.
    WlrLayershell.keyboardFocus: WlrKeyboardFocus.Exclusive

    // Everything in `scene` is rendered through the lens.
    Item {
      id: scene
      anchors.fill: parent
      layer.enabled: true
      layer.effect: ShaderEffect {
        property real strength: root.lensStrength
        property real aspect: root.sceneW / root.sceneH
        // No rim when flat, or the screen edge would stay darkened.
        property real feather: 0.0005 + 0.012 * Math.min(1, root.lensStrength * 4)
        property color frameColor: Qt.rgba(0, 0, 0, Math.min(1, root.reveal * 1.4))
        fragmentShader: Qt.resolvedUrl("shaders/lens.frag.qsb")
      }

      Image {
        anchors.fill: parent
        source: root.wallpaper
        fillMode: Image.PreserveAspectCrop
        sourceSize: Qt.size(root.sceneW, root.sceneH)
        asynchronous: true
        cache: false
        // Closing: stay opaque until the zoom has (nearly) landed on the real
        // window, so it never shows through behind a still-moving thumbnail.
        opacity: Math.min(1, root.reveal * (root.closing ? 8 : 3))
      }

      Rectangle { anchors.fill: parent; color: "black"; opacity: 0.72 * root.reveal * (1 - root.flatness) }
      Rectangle { anchors.fill: parent; color: root.bg; opacity: 0.22 * root.reveal * (1 - root.flatness) }

      ShaderEffect {
        anchors.fill: parent
        visible: root.cfg.showDots !== false
        opacity: 0.9 * root.reveal * (1 - root.flatness)
        readonly property real pitch: {
          var s = 56 * root.zoom
          while (s < 18) s *= 4
          return s
        }
        property size size: Qt.size(width, height)
        property point offset: Qt.point(root.panX, root.panY)
        property real spacing: pitch
        property real radius: 1.15
        property color dotColor: Util.alpha(root.fg, 0.28)
        fragmentShader: Qt.resolvedUrl("shaders/dots.frag.qsb")
      }

      Repeater {
        model: tileModel
        WindowTile {
          required property string modelData
          readonly property var rect: root.itemRect(modelData) || ({ x: 0, y: 0, w: 1, h: 1 })
          win: root.byAddr[modelData] || ({ address: modelData, title: "", appClass: "", workspaceName: "" })
          visible: !!root.byAddr[modelData]
          z: root.zOf(modelData)
          x: rect.x * root.zoom + root.panX
          y: rect.y * root.zoom + root.panY
          width: rect.w * root.zoom
          height: rect.h * root.zoom
          zoom: root.zoom
          reveal: root.reveal
          toplevel: root.toplevels[modelData] || null
          readonly property bool onScreen: x < root.sceneW && y < root.sceneH && x + width > 0 && y + height > 0
          capturing: (root.opened || root.closing) && onScreen
          live: root.cfg.liveThumbnails !== false
          opacity: root.closing && root.closeFocus && modelData !== root.closeFocus ? root.reveal : 1
          hovered: modelData === root.hoveredAddr || !!(root.dragAddr && root.dragGroup[modelData])
          dragging: !!(root.dragAddr && root.dragGroup[modelData])
          selected: modelData === root.selectedAddr && root.reveal > 0.5
          picked: !!root.picked[modelData]
          focusedWindow: !!(root.byAddr[modelData] && root.byAddr[modelData].focused)
          showLabel: root.cfg.showLabels === true
          accent: root.accent
          foreground: root.fg
          background: root.bg
          fontFamily: root.fontFamily
        }
      }

      // Attached windows: a short, subtle line bridging the gap between them.
      Repeater {
        model: ScriptModel { values: root.linkKeys }
        Rectangle {
          required property string modelData
          readonly property var pos: root.linkScenePos(modelData)
          readonly property var an: pos ? pos.an : null
          readonly property real ext: 4
          readonly property real thick: Math.max(1.5, Math.min(3, 6 * root.zoom))
          // Only a short bridge between neighbours; never a line across the canvas.
          readonly property real gap: !an ? 0 : an.horizontal ? an.x1 - an.x0 : an.y1 - an.y0
          visible: !!an && root.reveal > 0.02 && gap > 0 && gap <= 120
          opacity: 0.75 * root.reveal
          z: 100000
          color: root.accent
          radius: thick / 2
          x: !an ? 0 : an.horizontal ? an.x0 * root.zoom + root.panX - ext : pos.x - thick / 2
          y: !an ? 0 : an.horizontal ? pos.y - thick / 2 : an.y0 * root.zoom + root.panY - ext
          width: !an ? 0 : an.horizontal ? Math.max(2, (an.x1 - an.x0) * root.zoom) + ext * 2 : thick
          height: !an ? 0 : an.horizontal ? thick : Math.max(2, (an.y1 - an.y0) * root.zoom) + ext * 2
        }
      }

      // Right-drag selection box (drawn in canvas space, so it bends with the lens).
      Rectangle {
        readonly property var r: root.marquee
        visible: !!r
        z: 100001
        x: r ? r.x * root.zoom + root.panX : 0
        y: r ? r.y * root.zoom + root.panY : 0
        width: r ? r.w * root.zoom : 0
        height: r ? r.h * root.zoom : 0
        color: Util.alpha(root.accent, 0.08)
        border.width: 1
        border.color: Util.alpha(root.accent, 0.8)
      }

      // The "light up" as the view snaps flat.
      Rectangle {
        id: flash
        anchors.fill: parent
        z: 200000
        color: "white"
        opacity: 0
        SequentialAnimation {
          id: lightUp
          NumberAnimation { target: flash; property: "opacity"; to: 0.16; duration: 60; easing.type: Easing.OutQuad }
          NumberAnimation { target: flash; property: "opacity"; to: 0; duration: 320; easing.type: Easing.InQuad }
        }
      }

      Column {
        anchors.centerIn: parent
        spacing: 8
        visible: root.hasSnapshot && root.items.length === 0
        opacity: root.reveal
        Text {
          anchors.horizontalCenter: parent.horizontalCenter
          text: "No open windows"
          color: root.fg
          font.family: root.fontFamily
          font.pixelSize: Style.font.title
        }
        Text {
          anchors.horizontalCenter: parent.horizontalCenter
          text: "Open something and it will appear on the canvas. Esc closes."
          color: Util.alpha(root.fg, 0.55)
          font.family: root.fontFamily
          font.pixelSize: Style.font.caption
        }
      }
    }

    // Pointer interaction for the lensed scene.
    //   left:   click window = go there · drag window = move it (with its chain
    //           and the selection) · drag background = pan
    //   middle: click window = close it · drag = pan
    //   right:  drag = select windows · click window = unlink it (a selected
    //           group stays linked inside) · click background = clear selection
    MouseArea {
      id: pointer
      anchors.fill: parent
      hoverEnabled: true
      acceptedButtons: Qt.LeftButton | Qt.MiddleButton | Qt.RightButton
      enabled: root.opened && root.view === "canvas"
      cursorShape: root.dragAddr || mode === "pan" ? Qt.ClosedHandCursor
                   : mode === "select" ? Qt.CrossCursor
                   : (root.hoveredAddr ? Qt.OpenHandCursor : Qt.ArrowCursor)

      property real lastX: 0
      property real lastY: 0
      property real downX: 0
      property real downY: 0
      property int button: Qt.NoButton
      property string mode: ""        // "", "drag", "pan", "select"
      property string pressAddr: ""
      property real grabDX: 0
      property real grabDY: 0
      property var selectFrom: null

      // World point under the pointer; outside the lens rim fall back to the
      // unlensed position so a selection can still be dragged to the edge.
      function worldLoose(mx, my) {
        return root.worldAt(mx, my) || { x: (mx - root.panX) / root.zoom, y: (my - root.panY) / root.zoom }
      }

      onPressed: function(mouse) {
        lastX = downX = mouse.x
        lastY = downY = mouse.y
        button = mouse.button
        mode = ""
        pressAddr = root.itemAt(mouse.x, mouse.y)
        if (pressAddr && button === Qt.LeftButton) {
          var p = root.worldAt(mouse.x, mouse.y)
          var r = root.itemRect(pressAddr)
          grabDX = p.x - r.x
          grabDY = p.y - r.y
        }
      }
      onPositionChanged: function(mouse) {
        if (!pressed) {
          root.hoveredAddr = root.itemAt(mouse.x, mouse.y)
          return
        }
        if (!mode && Math.abs(mouse.x - downX) + Math.abs(mouse.y - downY) > 6) {
          if (button === Qt.RightButton) {
            mode = "select"
            selectFrom = worldLoose(downX, downY)
          } else if (button === Qt.LeftButton && pressAddr) {
            mode = "drag"
            root.startDrag(pressAddr)
          } else {
            mode = "pan"
          }
        }
        if (mode === "drag") {
          var p = root.worldAt(mouse.x, mouse.y)
          if (p) {
            var it = root.byAddr[root.dragAddr]
            var s = Model.snap({ x: p.x - grabDX, y: p.y - grabDY, w: it.w, h: it.h }, root.snapOthers(root.dragAddr), 14 / root.zoom)
            root.dragX = s.x
            root.dragY = s.y
          }
        } else if (mode === "pan") {
          root.panBy(mouse.x - lastX, mouse.y - lastY)
        } else if (mode === "select") {
          var q = worldLoose(mouse.x, mouse.y)
          var box = { x: Math.min(selectFrom.x, q.x), y: Math.min(selectFrom.y, q.y), w: Math.abs(q.x - selectFrom.x), h: Math.abs(q.y - selectFrom.y) }
          root.marquee = box
          root.selectInBox(box)
        }
        lastX = mouse.x
        lastY = mouse.y
      }
      onReleased: function(mouse) {
        var m = mode
        mode = ""
        if (m === "drag") { root.endDrag(); return }
        if (m === "select") { root.marquee = null; return }
        if (m === "pan") return
        var hit = root.itemAt(mouse.x, mouse.y)
        if (mouse.button === Qt.LeftButton) {
          if (hit) { root.focusItem(hit); return }
          root.picked = ({})
          var w = root.worldAt(mouse.x, mouse.y)
          if (w) root.landAt(w.x, w.y)
        } else if (mouse.button === Qt.RightButton) {
          if (hit) root.unlinkFor(hit)
          else root.picked = ({})
        } else if (mouse.button === Qt.MiddleButton) {
          if (hit) root.closeWindow(hit)
        }
      }
      onDoubleClicked: function(mouse) {
        if (mouse.button === Qt.LeftButton && !root.itemAt(mouse.x, mouse.y)) root.fitAll()
      }
      onExited: root.hoveredAddr = ""
      onWheel: function(wheel) {
        var s = root.lensMap(wheel.x, wheel.y) || { x: wheel.x, y: wheel.y }
        var touchpad = wheel.pixelDelta.x !== 0 || wheel.pixelDelta.y !== 0
        if (touchpad && !(wheel.modifiers & Qt.ControlModifier)) {
          root.panBy(wheel.pixelDelta.x, wheel.pixelDelta.y)
        } else {
          var dy = wheel.angleDelta.y !== 0 ? wheel.angleDelta.y : wheel.pixelDelta.y * 4
          root.zoomAt(s.x, s.y, Math.pow(1.0022, dy))
        }
      }
    }

    PinchHandler {
      target: null
      enabled: root.opened && root.view === "canvas"
      property real lastScale: 1
      onActiveChanged: lastScale = 1
      onActiveScaleChanged: {
        var f = activeScale / lastScale
        lastScale = activeScale
        var s = root.lensMap(centroid.position.x, centroid.position.y) || centroid.position
        poseAnim.stop()
        var nz = Math.max(root.minZoom, Math.min(root.maxZoom, root.zoom * f))
        var wx = (s.x - root.panX) / root.zoom, wy = (s.y - root.panY) / root.zoom
        if (root.flat) { if (f < 0.97) root.exitFlat(s.x, s.y); return }
        if (f > 1 && root.flatEnabled && nz >= root.flatThreshold * root.flatZoom) { root.enterFlat(s.x, s.y); return }
        root.zoom = nz
        root.panX = s.x - wx * nz
        root.panY = s.y - wy * nz
      }
    }

    // ── chrome (not lensed) ──────────────────────────────────────────

    Item {
      id: chrome
      anchors.fill: parent
      opacity: root.reveal * (root.view === "settings" ? 1 : 1 - root.flatness)
      visible: opacity > 0.01

      Text {
        anchors.left: parent.left
        anchors.bottom: parent.bottom
        anchors.margins: Style.space(18)
        text: "Click: go there  ·  Drag: move" + (root.attachEnabled ? " / link" : "") + "  ·  Right-drag: select  ·  Right-click: unlink  ·  Middle-click: close  ·  WASD / drag background: pan  ·  Q E: prev / next  ·  Scroll: zoom  ·  Ctrl+,: help & settings"
        color: Util.alpha(root.fg, 0.45)
        font.family: root.fontFamily
        font.pixelSize: Style.font.caption
        visible: root.view === "canvas" && root.cfg.showHints !== false
      }

      Rectangle {
        anchors.horizontalCenter: parent.horizontalCenter
        anchors.bottom: parent.bottom
        anchors.bottomMargin: Style.space(48)
        visible: opacity > 0
        opacity: root.toastText ? 1 : 0
        Behavior on opacity { NumberAnimation { duration: 150 } }
        width: toastLabel.implicitWidth + Style.space(24)
        height: toastLabel.implicitHeight + Style.space(12)
        radius: Math.max(2, Style.cornerRadius)
        color: Util.alpha(root.bg, 0.92)
        border.width: 1
        border.color: Util.alpha(root.accent, 0.6)
        Text {
          id: toastLabel
          anchors.centerIn: parent
          text: root.toastText
          color: root.fg
          font.family: root.fontFamily
          font.pixelSize: Style.font.body
        }
      }

      Text {
        anchors.horizontalCenter: parent.horizontalCenter
        anchors.top: parent.top
        anchors.topMargin: Style.space(18)
        visible: root.view === "canvas" && root.cfg.showHints !== false && root.pickedList().length > 0
        text: root.pickedList().length + " selected  ·  drag one to move them together  ·  right-click one to unlink the group from the rest  ·  Esc clears"
        color: root.accent
        font.family: root.fontFamily
        font.pixelSize: Style.font.caption
      }

      Minimap {
        visible: root.cfg.showMinimap !== false && root.items.length > 0
        anchors.right: parent.right
        anchors.bottom: toolRow.top
        anchors.rightMargin: Style.space(18)
        anchors.bottomMargin: Style.space(8)
        width: Style.space(170)
        height: Math.round(width * Math.min(0.75, Math.max(0.45, root.bounds.h / Math.max(1, root.bounds.w))))
        windows: root.items
        bounds: root.bounds
        viewport: root.viewport
        selectedAddr: root.selectedAddr
        onJump: function(wx, wy) {
          poseAnim.stop()
          root.setPose(root.zoom, wx, wy)
        }
      }

      Row {
        id: toolRow
        anchors.right: parent.right
        anchors.bottom: parent.bottom
        anchors.margins: Style.space(18)
        spacing: Style.space(6)

        Rectangle {
          width: Style.space(30); height: width
          radius: Math.max(2, Style.cornerRadius)
          color: fitMouse.containsMouse ? Util.alpha(root.fg, 0.16) : Util.alpha(root.bg, 0.8)
          border.width: 1
          border.color: Util.alpha(root.fg, 0.2)
          Grid {
            anchors.centerIn: parent
            columns: 3; spacing: 2
            Repeater { model: 9; Rectangle { width: 3; height: 3; color: root.accent } }
          }
          MouseArea {
            id: fitMouse
            anchors.fill: parent
            hoverEnabled: true
            cursorShape: Qt.PointingHandCursor
            onClicked: root.fitAll()
          }
        }

        Rectangle {
          width: Style.space(30); height: width
          radius: Math.max(2, Style.cornerRadius)
          color: setMouse.containsMouse || root.view === "settings" ? Util.alpha(root.fg, 0.16) : Util.alpha(root.bg, 0.8)
          border.width: 1
          border.color: Util.alpha(root.fg, 0.2)
          Column {
            anchors.centerIn: parent
            spacing: 3
            Repeater {
              model: [0.25, 0.7, 0.45]
              Item {
                required property var modelData
                width: 14; height: 3
                Rectangle { anchors.verticalCenter: parent.verticalCenter; width: parent.width; height: 1; color: Util.alpha(root.fg, 0.7) }
                Rectangle { x: parent.width * modelData - 2; anchors.verticalCenter: parent.verticalCenter; width: 4; height: 4; radius: 2; color: root.accent }
              }
            }
          }
          MouseArea {
            id: setMouse
            anchors.fill: parent
            hoverEnabled: true
            cursorShape: Qt.PointingHandCursor
            onClicked: root.view = root.view === "settings" ? "canvas" : "settings"
          }
        }
      }

      Rectangle {
        anchors.fill: parent
        color: Qt.rgba(0, 0, 0, 0.35)
        visible: root.view === "settings"
        MouseArea { anchors.fill: parent; onClicked: root.view = "canvas" }
      }

      SettingsPanel {
        id: settings
        anchors.centerIn: parent
        visible: root.view === "settings"
        host: root
        cfg: root.cfg
        onCloseRequested: { settings.reset(); root.view = "canvas" }
      }
    }

    Item {
      id: keyCatcher
      anchors.fill: parent
      focus: true
      z: -1

      Keys.priority: Keys.BeforeItem
      readonly property var panKeys: ({ 87: "w", 65: "a", 83: "s", 68: "d" })
      Keys.onReleased: function(event) {
        if (settings.handleKeyRelease(event)) { event.accepted = true; return }
        var pk = panKeys[event.key]
        if (pk) {
          if (!event.isAutoRepeat) root.holdPan(pk, false)
          event.accepted = true
        }
      }
      Keys.onPressed: function(event) {
        if (!root.opened) return
        if (settings.handleKeyPress(event)) { event.accepted = true; return }
        if (root.view === "settings" && settings.handleNavKey(event)) { event.accepted = true; return }
        var k = event.key
        var ctrl = event.modifiers & Qt.ControlModifier
        var shift = event.modifiers & Qt.ShiftModifier
        var step = 80
        if (k === Qt.Key_Escape) {
          if (root.view === "settings") { settings.reset(); root.view = "canvas" }
          else if (root.pickedList().length) root.picked = ({})
          else root.dismiss()
        } else if (ctrl && k === Qt.Key_Comma) {
          root.view = root.view === "settings" ? "canvas" : "settings"
        } else if (root.view === "settings") {
          return
        } else if (k === Qt.Key_Return || k === Qt.Key_Enter || k === Qt.Key_Space) {
          if (root.selectedAddr) root.focusItem(root.selectedAddr)
        } else if (shift && (k === Qt.Key_Left || k === Qt.Key_H)) {
          root.nudgeSelected(-step, 0)
        } else if (shift && (k === Qt.Key_Right || k === Qt.Key_L)) {
          root.nudgeSelected(step, 0)
        } else if (shift && (k === Qt.Key_Up || k === Qt.Key_K)) {
          root.nudgeSelected(0, -step)
        } else if (shift && (k === Qt.Key_Down || k === Qt.Key_J)) {
          root.nudgeSelected(0, step)
        } else if (k === Qt.Key_Left || k === Qt.Key_H) {
          root.selectBy(-1, 0)
        } else if (k === Qt.Key_Right || k === Qt.Key_L) {
          root.selectBy(1, 0)
        } else if (k === Qt.Key_Up || k === Qt.Key_K) {
          root.selectBy(0, -1)
        } else if (k === Qt.Key_Down || k === Qt.Key_J) {
          root.selectBy(0, 1)
        } else if (k === Qt.Key_Tab) {
          root.cycle(shift ? -1 : 1)
        } else if (k === Qt.Key_Backtab) {
          root.cycle(-1)
        } else if (k === Qt.Key_Plus || k === Qt.Key_Equal) {
          root.zoomAt(root.sceneW / 2, root.sceneH / 2, 1.25)
        } else if (k === Qt.Key_Minus) {
          root.zoomAt(root.sceneW / 2, root.sceneH / 2, 0.8)
        } else if (keyCatcher.panKeys[k] && !(event.modifiers & (Qt.ControlModifier | Qt.AltModifier | Qt.MetaModifier))) {
          if (!event.isAutoRepeat) root.holdPan(keyCatcher.panKeys[k], true)
        } else if (k === Qt.Key_Q) {
          root.jump(-1)
        } else if (k === Qt.Key_E) {
          root.jump(1)
        } else if (k === Qt.Key_U) {
          if (root.selectedAddr) root.unlinkAll(root.selectedAddr)
        } else if (k === Qt.Key_0 || k === Qt.Key_F) {
          root.fitAll()
        } else {
          return
        }
        event.accepted = true
      }
    }
  }

  function poseAnim_stop() { poseAnim.stop() }
}
